version: "3.8"
services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    volumes:
      - ./volumes/mongo_db/data:/data/db
    networks:
      - scout-net
  gens:
    build: .
    volumes:
      - ./utils:/home/worker/app/utils
      - ./gens:/home/worker/app/gens
      - ./volumes/gens/data:/home/worker/data
      - ./volumes/gens/wgs:/access/wgs
        #- /media/isilon/backup_hopper/results/wgs:/access/wgs
    environment:
      - FLASK_ENV=development
      - MONGODB_HOST=mongo_db
      - MONGODB_PORT=27017
      - SCOUT_DBNAME=scout
      - GENS_DBNAME=gens
    expose:
      - '5000'
    ports:
      - "5003:5000"
    networks:
      - scout-net
    depends_on:
      - mongo_db
    command: "flask run --host 0.0.0.0"
  scout:
    image: clinicalgenomics/scout
    container_name: scout
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: scout --host mongo_db serve --host 0.0.0.0
    networks:
      - scout-net
    depends_on:
      - mongo_db
networks:
  scout-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
