version: "3.9"
services:
  mongodb:
    image: mongo:4.4.22
    volumes:
      - ./volumes/mongo_db/data:/data/db
    networks:
      - gens-net
  frontend:
    build: .
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - GENS_API_URL=http://api:5001/
    expose:
      - '5000'
    ports:
      - "5000:5000"
    networks:
      - gens-net
    depends_on:
      - mongodb
      - api
      - mongodb
    command: "flask run --host 0.0.0.0"

  api:
    build:
      context: api
      network: host
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - ALLOWED_ORIGINS=*
    ports:
      - "5001:8000"
    volumes:
      - ./volumes/gens/data:/home/app/data
      - ./volumes/gens/wgs:/home/app/access/wgs
    networks:
      - gens-net
    depends_on:
      - mongodb
    command: "uvicorn app.main:app --reload --host 0.0.0.0"

networks:
  gens-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
