version: "3.8"
services:
  markus_mongodb:
    container_name: markus_mongodb
    image: mongo
    volumes:
      - ./volumes/mongo_db/data:/data/db
    networks:
      - gens-net
  markus_gens:
    container_name: markus_gens
    build: .
    volumes:
      - ./utils:/home/app/app/utils
      - ./gens:/home/app/app/gens
      - ./volumes/gens/data:/home/app/data
      - ./volumes/gens/wgs:/home/app/access/wgs
        #- /media/isilon/backup_hopper/results/wgs:/access/wgs
    environment:
      - FLASK_APP=gens/app.py
      - FLASK_ENV=development
      - MONGODB_HOST=markus_mongodb
      - MONGODB_PORT=27017
      - SCOUT_DBNAME=scout
      - GENS_DBNAME=gens
    expose:
      - '5000'
    ports:
      - "5003:5000"
    networks:
      - gens-net
    depends_on:
      - markus_mongodb
    command: "flask run --host 0.0.0.0"
networks:
  gens-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
