version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:7
    volumes:
      - ./volumes/mongo_db/data:/data/db
    networks:
      - gens-net

  gens:
    container_name: gens
    build: .
    volumes:
      - ./utils:/home/app/app/utils
      - ./gens:/home/app/app/gens
      - ./setup.py:/home/app/app/setup.py
      - ./volumes/gens/data:/home/app/data
      - ./volumes/gens/wgs:/home/app/access/wgs
        #- /media/isilon/backup_hopper/results/wgs:/access/wgs
    environment:
      - FLASK_APP=gens/app.py
      - FLASK_ENV=development
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - SCOUT_DBNAME=scout
      - GENS_DBNAME=gens
    expose:
      - '5000'
    ports:
      - "5000:5000"
    networks:
      - gens-net
    depends_on:
      - mongodb
      - api
    command: "flask run --host 0.0.0.0"

  api:
    container_name: api
    build:
      context: api
      network: host
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    expose:
      - '5000'
    ports:
      - "5001:5000"
    networks:
      - gens-net
    depends_on:
      - mongodb
    command: "uvicorn app.main:app --reload --host 0.0.0.0"

networks:
  gens-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
